<?php
// top header
Redux::set_section( $opt_name, array(
	'title'  => esc_html__( 'Header', 'travelwp' ), 
	'id'     => 'header',
	'icon'   => 'el el-tasks',
	'fields' => array(
		array(
			'id'    => 'info_header_',
			'type'  => 'info',
			'style' => 'info',
			'class' =>  'margin-btn-30 hide ' . travelwp_theme_options_extral_class('header'),
			'desc'  => sprintf(__('This Header is built by Thim Elementor Kit, you can edit and configure it in %s.', 'travelwp'), '<a href="' . admin_url('edit.php?post_type=thim_elementor_kit&thim_elementor_type=header') . '" target="_blank">' . __('Thim Elementor Kit', 'travelwp') . '</a>'),
		),
		array(
			'id'      => 'top_bar',
			'type'    => 'switch',
			'title'   => esc_html__( 'Top Bar', 'travelwp' ),
			'default' => 0,
			'on'      => 'Show',
			'off'     => 'Hide',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'       => 'bg_top_bar',
			'type'     => 'color_rgba',
			'title'    => esc_html__( 'Background Color', 'travelwp' ),
			'required' => array( 'top_bar', '=', '1' ),
			'default'  => '#414b4f',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'          => 'text_color_top_bar',
			'type'        => 'color',
			'title'       => esc_html__( 'Text Color', 'travelwp' ),
			'required'    => array( 'top_bar', '=', '1' ),
			'transparent' => false,
			'default'     => '#cccccc',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),

		array(
			'id'          => 'link_color_top_bar',
			'type'        => 'color',
			'title'       => esc_html__( 'Link Color', 'travelwp' ),
			'required'    => array( 'top_bar', '=', '1' ),
			'transparent' => false,
			'default'     => '#fff',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),

		array(
			'id'   => 'main_menu_info_styling',
			'type' => 'info',
			'raw'  => esc_html__( 'Main Menu', 'travelwp' ),
			'class' =>  travelwp_theme_options_extral_class('header'),
		),

		array(
			'id'      => 'bg_header_color',
			'type'    => 'color_rgba',
			'title'   => esc_html__( 'Background header', 'travelwp' ),
			'default' => array(
				'color' => '#fff',
				'alpha' => '1'
			),
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'          => 'text_menu_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Text Menu Color', 'travelwp' ),
			'transparent' => false,
			'default'     => '#333',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'      => 'font_size_main_menu',
			'type'    => 'spinner',
			'title'   => esc_html__( 'Font Size (px)', 'travelwp' ),
			'default' => '14',
			'min'     => '1',
			'step'    => '1',
			'max'     => '50',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'      => 'font_weight_main_menu',
			'type'    => 'select',
			'title'   => esc_html__( 'Font Weight', 'travelwp' ),
			'options' => array(
				'normal'  => 'Normal',
				'bold'    => 'Bold',
				'lighter' => 'Lighter',
				'100'     => '100',
				'200'     => '200',
				'300'     => '300',
				'400'     => '400',
				'500'     => '500',
				'600'     => '600',
				'700'     => '700',
				'800'     => '800',
				'900'     => '900',
			),
			'default' => 'normal',
			'select2' => array( 'allowClear' => false ),
			'class' =>  travelwp_theme_options_extral_class('header'),
		),

		array(
			'id'      => 'sticky_menu',
			'type'    => 'switch',
			'title'   => esc_html__( 'Sticky Menu', 'travelwp' ),
			'default' => 0,
			'on'      => 'Show',
			'off'     => 'Hide',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'       => 'sticky_custom_menu',
			'type'     => 'switch',
			'title'    => esc_html__( 'Sticky Menu Option', 'travelwp' ),
			'default'  => 0,
			'on'       => 'Custom',
			'off'      => 'Default',
			'required' => array( 'sticky_menu', '=', '1' ),
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'       => 'bg_sticky_menu',
			'type'     => 'color_rgba',
			'title'    => esc_html__( 'Sticky Menu Background Color', 'travelwp' ),
			'required' => array( 'sticky_custom_menu', '=', '1' ),
			'default'  => array(
				'color' => '#fff',
				'alpha' => '1'
			),
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'          => 'text_color_sticky_menu',
			'type'        => 'color',
			'title'       => esc_html__( 'Sticky Menu Text Color', 'travelwp' ),
			'required'    => array( 'sticky_custom_menu', '=', '1' ),
			'transparent' => false,
			'default'     => '#333',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),

		array(
			'id'   => 'sub_menu',
			'type' => 'info',
			'raw'  => esc_html__( 'Sub Menu', 'travelwp' ),
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'          => 'sub_menu_bg_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Background Color', 'travelwp' ),
			'transparent' => false,
			'default'     => '#fff',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'          => 'sub_menu_text_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Text Color', 'travelwp' ),
			'transparent' => false,
			'default'     => '#333',
			'class' =>  travelwp_theme_options_extral_class('header'),

		),
		array(
			'id'          => 'sub_menu_text_hover_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Text Hover Color', 'travelwp' ),
			'transparent' => false,
			'default'     => '#ffb300',
			'class' =>  travelwp_theme_options_extral_class('header'),

		),
		array(
			'id'   => 'mobile_menu',
			'type' => 'info',
			'raw'  => esc_html__( 'Mobile Menu', 'travelwp' ),
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'          => 'mobile_menu_bg_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Background Color', 'travelwp' ),
			'transparent' => false,
			'default'     => '#232323',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'          => 'mobile_menu_text_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Text Color', 'travelwp' ),
			'transparent' => false,
			'default'     => '#fff',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
		array(
			'id'          => 'mobile_text_hover_color',
			'type'        => 'color',
			'title'       => esc_html__( 'Text Hover Color', 'travelwp' ),
			'transparent' => false,
			'default'     => '#ffb300',
			'class' =>  travelwp_theme_options_extral_class('header'),
		),
	)
) );
